import 'package:verbatica/model/Chat.dart';

final List<Chat> dummyChats = [
  Chat(
    chatId: "chat_0",
    participantIds: ["27", "2"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 0)),
    lastMessageSeenBy: {"27": false, "2": false},
    isTyping: {"27": false, "2": true},
    userProfiles: {"27": "27", "2": "2"},
    userNames: {"27": "BlueSkies_123", "2": "FancyBanana_456"},
    lastMessage: "Hey, are you coming to the event tonight?",
  ),
  Chat(
    chatId: "chat_1",
    participantIds: ["27", "3"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 5)),
    lastMessageSeenBy: {"27": true, "3": false},
    isTyping: {"27": false, "3": true},
    userProfiles: {"27": "27", "3": "3"},
    userNames: {"27": "BlueSkies_123", "3": "SneakyPenguin_789"},
    lastMessage: "I'll send you the files once I get home.",
  ),
  Chat(
    chatId: "chat_2",
    participantIds: ["27", "4"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 10)),
    lastMessageSeenBy: {"27": false, "4": true},
    isTyping: {"27": true, "4": false},
    userProfiles: {"27": "27", "4": "4"},
    userNames: {"27": "BlueSkies_123", "4": "QuietTiger_101"},
    lastMessage: "Did you watch the new episode yet?",
  ),
  Chat(
    chatId: "chat_3",
    participantIds: ["27", "5"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 15)),
    lastMessageSeenBy: {"27": true, "5": false},
    isTyping: {"27": false, "5": true},
    userProfiles: {"27": "27", "5": "5"},
    userNames: {"27": "BlueSkies_123", "5": "CharmingFox_202"},
    lastMessage: "Let’s catch up this weekend!",
  ),
  Chat(
    chatId: "chat_4",
    participantIds: ["27", "6"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 20)),
    lastMessageSeenBy: {"27": false, "6": true},
    isTyping: {"27": true, "6": false},
    userProfiles: {"27": "27", "6": "6"},
    userNames: {"27": "BlueSkies_123", "6": "MysticOwl_303"},
    lastMessage: "I’ve completed the draft, take a look.",
  ),
  Chat(
    chatId: "chat_5",
    participantIds: ["27", "7"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 25)),
    lastMessageSeenBy: {"27": true, "7": false},
    isTyping: {"27": false, "7": true},
    userProfiles: {"27": "27", "7": "7"},
    userNames: {"27": "BlueSkies_123", "7": "SilentLion_404"},
    lastMessage: "Are we still on for tomorrow?",
  ),
  Chat(
    chatId: "chat_6",
    participantIds: ["27", "8"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 30)),
    lastMessageSeenBy: {"27": false, "8": true},
    isTyping: {"27": true, "8": false},
    userProfiles: {"27": "27", "8": "8"},
    userNames: {"27": "BlueSkies_123", "8": "HappyGiraffe_505"},
    lastMessage: "Thanks for the recommendation!",
  ),
  Chat(
    chatId: "chat_7",
    participantIds: ["27", "2"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 35)),
    lastMessageSeenBy: {"27": true, "2": false},
    isTyping: {"27": false, "2": true},
    userProfiles: {"27": "27", "2": "2"},
    userNames: {"27": "BlueSkies_123", "2": "FancyBanana_456"},
    lastMessage: "I'll call you after my meeting.",
  ),
  Chat(
    chatId: "chat_8",
    participantIds: ["27", "3"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 40)),
    lastMessageSeenBy: {"27": false, "3": true},
    isTyping: {"27": true, "3": false},
    userProfiles: {"27": "27", "3": "3"},
    userNames: {"27": "BlueSkies_123", "3": "SneakyPenguin_789"},
    lastMessage: "Let me know if you need help.",
  ),
  Chat(
    chatId: "chat_9",
    participantIds: ["27", "4"],
    lastUpdated: DateTime.now().subtract(Duration(minutes: 45)),
    lastMessageSeenBy: {"27": false, "4": false},
    isTyping: {"27": false, "4": true},
    userProfiles: {"27": "27", "4": "4"},
    userNames: {"27": "BlueSkies_123", "4": "QuietTiger_101"},
    lastMessage: "I got your message, thanks!",
  ),
];
