import 'package:verbatica/model/comment.dart';

List<Comment> dummyComments = [
  Comment(
    id: '1',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #1: Root level comment.',
    author: 'User1',
    profile: '1',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(days: 5)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [
      Comment(
        id: '2',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'Comment #2: Reply to #1.',
        author: 'User2',
        profile: '2',
        parentId: '1',
        uploadTime: DateTime.now().subtract(const Duration(days: 4)),
        isUpvote: false,
        isDownvote: false,
        allReplies: [],
      ),
    ],
  ),
  Comment(
    id: '3',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #3: Independent top-level comment.',
    author: 'User3',
    profile: '3',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(days: 3, hours: 5)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [],
  ),
  Comment(
    id: '4',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #4: Root comment starting a deep thread.',
    author: 'User4',
    profile: '4',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(days: 4, hours: 3)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [
      Comment(
        id: '5',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'Comment #5: Reply to #4.',
        author: 'User5',
        profile: '5',
        parentId: '4',
        uploadTime: DateTime.now().subtract(const Duration(days: 3, hours: 18)),
        isUpvote: false,
        isDownvote: false,
        allReplies: [
          Comment(
            id: '6',
            postId: 'post_1',
            titleOfThePost: 'Debating Social Media Etiquette',
            text: 'Comment #6: Reply to #5.',
            author: 'User6',
            profile: '6',
            parentId: '5',
            uploadTime: DateTime.now().subtract(
              const Duration(days: 2, hours: 6),
            ),
            isUpvote: false,
            isDownvote: false,
            allReplies: [
              Comment(
                id: '7',
                postId: 'post_1',
                titleOfThePost: 'Debating Social Media Etiquette',
                text: 'Comment #7: Reply to #6 (Level 4).',
                author: 'User7',
                profile: '7',
                parentId: '6',
                uploadTime: DateTime.now().subtract(
                  const Duration(days: 1, hours: 12),
                ),
                isUpvote: false,
                isDownvote: false,
                allReplies: [],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '8',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #8: Independent top-level comment.',
    author: 'User8',
    profile: '8',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(days: 2, hours: 8)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [],
  ),
  Comment(
    id: '9',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #9: Root with one reply.',
    author: 'User9',
    profile: '9',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(days: 2)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [
      Comment(
        id: '10',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'Comment #10: Reply to #9.',
        author: 'User10',
        profile: '10',
        parentId: '9',
        uploadTime: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
        isUpvote: false,
        isDownvote: false,
        allReplies: [],
      ),
    ],
  ),
  Comment(
    id: '11',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #11: Simple comment with no replies.',
    author: 'User11',
    profile: '11',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(hours: 15)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [],
  ),
  Comment(
    id: '12',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'Comment #12: Root leading to two nested replies.',
    author: 'User12',
    profile: '12',
    parentId: null,
    uploadTime: DateTime.now().subtract(const Duration(hours: 20)),
    isUpvote: false,
    isDownvote: false,
    allReplies: [
      Comment(
        id: '13',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'Comment #13: Reply to #12.',
        author: 'User13',
        profile: '13',
        parentId: '12',
        uploadTime: DateTime.now().subtract(const Duration(hours: 16)),
        isUpvote: false,
        isDownvote: false,
        allReplies: [
          Comment(
            id: '14',
            postId: 'post_1',
            titleOfThePost: 'Debating Social Media Etiquette',
            text: 'Comment #14: Reply to #13 (Level 3).',
            author: 'User14',
            profile: '14',
            parentId: '13',
            uploadTime: DateTime.now().subtract(const Duration(hours: 10)),
            isUpvote: false,
            isDownvote: false,
            allReplies: [
              Comment(
                id: '15',
                postId: 'post_1',
                titleOfThePost: 'Debating Social Media Etiquette',
                text: 'Comment #15: Reply to #14 (Level 4).',
                author: 'User15',
                profile: '15',
                parentId: '14',
                uploadTime: DateTime.now().subtract(const Duration(hours: 4)),
                isUpvote: false,
                isDownvote: false,
                allReplies: [],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
];
