import 'package:verbatica/model/comment.dart';

List<Comment> dummyComments = [
  Comment(
    id: '1',
    postId: 'post_1',
    text: 'This is comment #1, level 1',
    author: 'User2',
    profile: '5',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 2)),
    upVotes: 15,
    downVotes: 3,
    allReplies: [
      Comment(
        id: '2',
        postId: 'post_1',
        text: 'This is comment #2, level 2',
        author: 'User4',
        profile: '3',
        parentId: '1',
        uploadTime: DateTime.now().subtract(Duration(days: 1)),
        upVotes: 8,
        downVotes: 2,
        allReplies: [
          Comment(
            id: '3',
            postId: 'post_1',
            text: 'This is comment #3, level 3',
            author: 'User3',
            profile: '2',
            parentId: '2',
            uploadTime: DateTime.now().subtract(Duration(hours: 5)),
            upVotes: 5,
            downVotes: 0,
            allReplies: [],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '4',
    postId: 'post_1',
    text: 'This is comment #2, level 1',
    author: 'User1',
    profile: '2',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 4)),
    upVotes: 12,
    downVotes: 4,
    allReplies: [
      Comment(
        id: '5',
        postId: 'post_1',
        text: 'This is comment #3, level 2',
        author: 'User2',
        profile: '5',
        parentId: '4',
        uploadTime: DateTime.now().subtract(Duration(days: 3)),
        upVotes: 6,
        downVotes: 1,
        allReplies: [
          Comment(
            id: '6',
            postId: 'post_1',
            text: 'This is comment #4, level 3',
            author: 'User3',
            profile: '3',
            parentId: '5',
            uploadTime: DateTime.now().subtract(Duration(days: 2)),
            upVotes: 3,
            downVotes: 0,
            allReplies: [],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '7',
    postId: 'post_1',
    text: 'This is comment #3, level 1',
    author: 'User5',
    profile: '1',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 5)),
    upVotes: 20,
    downVotes: 5,
    allReplies: [],
  ),
  Comment(
    id: '8',
    postId: 'post_1',
    text: 'This is comment #4, level 1',
    author: 'User1',
    profile: '3',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 3)),
    upVotes: 10,
    downVotes: 2,
    allReplies: [
      Comment(
        id: '9',
        postId: 'post_1',
        text: 'This is comment #5, level 2',
        author: 'User3',
        profile: '4',
        parentId: '8',
        uploadTime: DateTime.now().subtract(Duration(days: 2)),
        upVotes: 7,
        downVotes: 1,
        allReplies: [
          Comment(
            id: '10',
            postId: 'post_1',
            text: 'This is comment #6, level 3',
            author: 'User2',
            profile: '5',
            parentId: '9',
            uploadTime: DateTime.now().subtract(Duration(days: 1)),
            upVotes: 4,
            downVotes: 0,
            allReplies: [],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '11',
    postId: 'post_1',
    text: 'This is comment #5, level 1',
    author: 'User4',
    profile: '2',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 6)),
    upVotes: 5,
    downVotes: 3,
    allReplies: [],
  ),
  // Deep nested comment chain (Level 1 to Level 10)
  Comment(
    id: '6',
    postId: 'post_1',
    text: 'Level 1 deep thread',
    author: 'UserA',
    profile: '1',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 1)),
    upVotes: 50,
    downVotes: 1,
    allReplies: [
      Comment(
        id: '61',
        postId: 'post_1',
        text: 'Level 2 reply',
        author: 'UserB',
        profile: '2',
        parentId: '6',
        uploadTime: DateTime.now().subtract(Duration(hours: 20)),
        upVotes: 45,
        downVotes: 1,
        allReplies: [
          Comment(
            id: '62',
            postId: 'post_1',
            text: 'Level 3 reply',
            author: 'UserC',
            profile: '3',
            parentId: '61',
            uploadTime: DateTime.now().subtract(Duration(hours: 18)),
            upVotes: 40,
            downVotes: 2,
            allReplies: [
              Comment(
                id: '63',
                postId: 'post_1',
                text: 'Level 4 reply',
                author: 'UserD',
                profile: '4',
                parentId: '62',
                uploadTime: DateTime.now().subtract(Duration(hours: 16)),
                upVotes: 35,
                downVotes: 1,
                allReplies: [
                  Comment(
                    id: '64',
                    postId: 'post_1',
                    text: 'Level 5 reply',
                    author: 'UserE',
                    profile: '5',
                    parentId: '63',
                    uploadTime: DateTime.now().subtract(Duration(hours: 14)),
                    upVotes: 30,
                    downVotes: 2,
                    allReplies: [
                      Comment(
                        id: '65',
                        postId: 'post_1',
                        text: 'Level 6 reply',
                        author: 'UserF',
                        profile: '1',
                        parentId: '64',
                        uploadTime: DateTime.now().subtract(
                          Duration(hours: 12),
                        ),
                        upVotes: 25,
                        downVotes: 2,
                        allReplies: [
                          Comment(
                            id: '66',
                            postId: 'post_1',
                            text: 'Level 7 reply',
                            author: 'UserG',
                            profile: '2',
                            parentId: '65',
                            uploadTime: DateTime.now().subtract(
                              Duration(hours: 10),
                            ),
                            upVotes: 20,
                            downVotes: 1,
                            allReplies: [
                              Comment(
                                id: '67',
                                postId: 'post_1',
                                text: 'Level 8 reply',
                                author: 'UserH',
                                profile: '3',
                                parentId: '66',
                                uploadTime: DateTime.now().subtract(
                                  Duration(hours: 8),
                                ),
                                upVotes: 15,
                                downVotes: 1,
                                allReplies: [],
                              ),
                              Comment(
                                id: '68',
                                postId: 'post_1',
                                text: 'Level 8 reply',
                                author: 'UserH',
                                profile: '7',
                                parentId: '66',
                                uploadTime: DateTime.now().subtract(
                                  Duration(hours: 8),
                                ),
                                upVotes: 20,
                                downVotes: 1,
                                allReplies: [],
                              ),
                              Comment(
                                id: '69',
                                postId: 'post_1',
                                text: 'Level 8 reply',
                                author: 'UserH',
                                profile: '6',
                                parentId: '66',
                                uploadTime: DateTime.now().subtract(
                                  Duration(hours: 8),
                                ),
                                upVotes: 15,
                                downVotes: 1,
                                allReplies: [],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              Comment(
                id: '11',
                postId: 'post_1',
                text: 'This is comment #dontknow, level 4',
                author: 'User4',
                profile: '8',
                parentId: '3',
                uploadTime: DateTime.now().subtract(Duration(days: 6)),
                upVotes: 5,
                downVotes: 3,
                allReplies: [],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
];
