import 'package:verbatica/model/comment.dart';

List<Comment> dummyComments = [
  Comment(
    id: '1',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'This is comment #1, level 1',
    author: 'User2',
    profile: '5',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 2)),
    upVoteUserIds: ['1', "2", "5"],
    downVoteUserIds: ['3'],
    allReplies: [
      Comment(
        id: '2',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'This is comment #2, level 2',
        author: 'User4',
        profile: '3',
        parentId: '1',
        uploadTime: DateTime.now().subtract(Duration(days: 1)),
        upVoteUserIds: ['2'],
        downVoteUserIds: ['4'],
        allReplies: [
          Comment(
            id: '3',
            postId: 'post_1',
            titleOfThePost: 'Debating Social Media Etiquette',
            text: 'This is comment #3, level 3',
            author: 'User3',
            profile: '2',
            parentId: '2',
            uploadTime: DateTime.now().subtract(Duration(hours: 5)),
            upVoteUserIds: ['1'],
            downVoteUserIds: [],
            allReplies: [],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '4',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'This is comment #2, level 1',
    author: 'User1',
    profile: '2',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 4)),
    upVoteUserIds: ['1', '2'],
    downVoteUserIds: ['3'],
    allReplies: [
      Comment(
        id: '5',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'This is comment #3, level 2',
        author: 'User2',
        profile: '5',
        parentId: '4',
        uploadTime: DateTime.now().subtract(Duration(days: 3)),
        upVoteUserIds: ['2'],
        downVoteUserIds: ['1'],
        allReplies: [
          Comment(
            id: '6a',
            postId: 'post_1',
            titleOfThePost: 'Debating Social Media Etiquette',
            text: 'This is comment #4, level 3',
            author: 'User3',
            profile: '3',
            parentId: '5',
            uploadTime: DateTime.now().subtract(Duration(days: 2)),
            upVoteUserIds: ['1'],
            downVoteUserIds: [],
            allReplies: [],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '7',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'This is comment #3, level 1',
    author: 'User5',
    profile: '1',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 5)),
    upVoteUserIds: ['1', '5'],
    downVoteUserIds: ['3'],
    allReplies: [],
  ),
  Comment(
    id: '8',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'This is comment #4, level 1',
    author: 'User1',
    profile: '3',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 3)),
    upVoteUserIds: ['1'],
    downVoteUserIds: ['2'],
    allReplies: [
      Comment(
        id: '9',
        postId: 'post_1',
        titleOfThePost: 'Debating Social Media Etiquette',
        text: 'This is comment #5, level 2',
        author: 'User3',
        profile: '4',
        parentId: '8',
        uploadTime: DateTime.now().subtract(Duration(days: 2)),
        upVoteUserIds: ['2'],
        downVoteUserIds: [],
        allReplies: [
          Comment(
            id: '10',
            postId: 'post_1',
            titleOfThePost: 'Debating Social Media Etiquette',
            text: 'This is comment #6, level 3',
            author: 'User2',
            profile: '5',
            parentId: '9',
            uploadTime: DateTime.now().subtract(Duration(days: 1)),
            upVoteUserIds: ['1'],
            downVoteUserIds: [],
            allReplies: [],
          ),
        ],
      ),
    ],
  ),
  Comment(
    id: '11a',
    postId: 'post_1',
    titleOfThePost: 'Debating Social Media Etiquette',
    text: 'This is comment #5, level 1',
    author: 'User4',
    profile: '2',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 6)),
    upVoteUserIds: ['2'],
    downVoteUserIds: ['3'],
    allReplies: [],
  ),
  Comment(
    id: '12',
    postId: 'post_1',
    titleOfThePost: 'Deep Nested Comment Test',
    text: 'Level 1 deep thread',
    author: 'UserA',
    profile: '1',
    parentId: null,
    uploadTime: DateTime.now().subtract(Duration(days: 1)),
    upVoteUserIds: ['1', "3", '4', '5', '6'],
    downVoteUserIds: ['2'],
    allReplies: [
      Comment(
        id: '13',
        postId: 'post_1',
        titleOfThePost: 'Deep Nested Comment Test',
        text: 'Level 2 reply',
        author: 'UserB',
        profile: '2',
        parentId: '12',
        uploadTime: DateTime.now().subtract(Duration(hours: 20)),
        upVoteUserIds: ['1'],
        downVoteUserIds: [],
        allReplies: [
          Comment(
            id: '14',
            postId: 'post_1',
            titleOfThePost: 'Deep Nested Comment Test',
            text: 'Level 3 reply',
            author: 'UserC',
            profile: '3',
            parentId: '13',
            uploadTime: DateTime.now().subtract(Duration(hours: 18)),
            upVoteUserIds: ['1'],
            downVoteUserIds: ['2'],
            allReplies: [
              Comment(
                id: '15',
                postId: 'post_1',
                titleOfThePost: 'Deep Nested Comment Test',
                text: 'Level 4 reply',
                author: 'UserD',
                profile: '4',
                parentId: '14',
                uploadTime: DateTime.now().subtract(Duration(hours: 16)),
                upVoteUserIds: ['1'],
                downVoteUserIds: ['3'],
                allReplies: [
                  Comment(
                    id: '16',
                    postId: 'post_1',
                    titleOfThePost: 'Deep Nested Comment Test',
                    text: 'Level 5 reply',
                    author: 'UserE',
                    profile: '5',
                    parentId: '15',
                    uploadTime: DateTime.now().subtract(Duration(hours: 14)),
                    upVoteUserIds: ['2'],
                    downVoteUserIds: [],
                    allReplies: [
                      Comment(
                        id: '17',
                        postId: 'post_1',
                        titleOfThePost: 'Deep Nested Comment Test',
                        text: 'Level 6 reply',
                        author: 'UserF',
                        profile: '1',
                        parentId: '16',
                        uploadTime: DateTime.now().subtract(
                          Duration(hours: 12),
                        ),
                        upVoteUserIds: ['1'],
                        downVoteUserIds: [],
                        allReplies: [
                          Comment(
                            id: '18',
                            postId: 'post_1',
                            titleOfThePost: 'Deep Nested Comment Test',
                            text: 'Level 7 reply',
                            author: 'UserG',
                            profile: '2',
                            parentId: '17',
                            uploadTime: DateTime.now().subtract(
                              Duration(hours: 10),
                            ),
                            upVoteUserIds: ['1'],
                            downVoteUserIds: [],
                            allReplies: [
                              Comment(
                                id: '19',
                                postId: 'post_1',
                                titleOfThePost: 'Deep Nested Comment Test',
                                text: 'Level 8 reply',
                                author: 'UserH',
                                profile: '3',
                                parentId: '18',
                                uploadTime: DateTime.now().subtract(
                                  Duration(hours: 8),
                                ),
                                upVoteUserIds: ['1'],
                                downVoteUserIds: [],
                                allReplies: [],
                              ),
                              Comment(
                                id: '20',
                                postId: 'post_1',
                                titleOfThePost: 'Deep Nested Comment Test',
                                text: 'Level 8 reply',
                                author: 'UserH',
                                profile: '7',
                                parentId: '18',
                                uploadTime: DateTime.now().subtract(
                                  Duration(hours: 8),
                                ),
                                upVoteUserIds: ['1'],
                                downVoteUserIds: [],
                                allReplies: [],
                              ),
                              Comment(
                                id: '21',
                                postId: 'post_1',
                                titleOfThePost: 'Deep Nested Comment Test',
                                text: 'Level 8 reply',
                                author: 'UserH',
                                profile: '6',
                                parentId: '18',
                                uploadTime: DateTime.now().subtract(
                                  Duration(hours: 8),
                                ),
                                upVoteUserIds: ['2'],
                                downVoteUserIds: [],
                                allReplies: [],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  Comment(
                    id: '22',
                    postId: 'post_1',
                    titleOfThePost: 'Deep Nested Comment Test',
                    text: 'Side comment at level 4',
                    author: 'User4',
                    profile: '8',
                    parentId: '14',
                    uploadTime: DateTime.now().subtract(Duration(hours: 15)),
                    upVoteUserIds: ['1'],
                    downVoteUserIds: ['2'],
                    allReplies: [],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
];
