// Generate dummy posts
import 'package:verbatica/model/Post.dart';

// List 1: 3 clusters
List<Cluster> clusters1 = [
  Cluster(id: '1', title: 'Technology'),
  Cluster(id: '2', title: 'Science'),
  Cluster(id: '3', title: 'Programming'),
];

// List 2: 4 clusters
List<Cluster> clusters2 = [
  Cluster(id: '4', title: 'Sports'),
  Cluster(id: '5', title: 'Health'),
  Cluster(id: '6', title: 'Fitness'),
  Cluster(id: '7', title: 'Nutrition'),
];

// List 3: 2 clusters
List<Cluster> clusters3 = [
  Cluster(id: '8', title: 'Art'),
  Cluster(id: '9', title: 'Music'),
];
List<Post> forYouPosts = [
  Post(
    id: '1',
    name: 'Tech News',
    avatar: 1,
    title: 'New Smartphone Released',
    description:
        'The latest flagship phone with revolutionary camera technology has been unveiled today.',
    postImageLink: 'https://picsum.photos/500/300?random=1',
    isDebate: false,
    upvotes: 245,
    downvotes: 22,
    isUpVote: true,
    isDownVote: false,
    comments: 32,
    uploadTime: DateTime.now().subtract(Duration(hours: 2)),
  ),
  Post(
    id: '2',
    name: 'Travel Enthusiast',
    avatar: 1,
    title: 'Hidden Beach in Thailand',
    description:
        'Found this amazing secluded beach that most tourists don\'t know about!',
    postImageLink: 'https://picsum.photos/500/300?random=2',
    isDebate: false,
    upvotes: 45,
    downvotes: 22,
    isUpVote: false,
    isDownVote: true,
    comments: 24,
    uploadTime: DateTime.now().subtract(Duration(hours: 5)),
  ),
  Post(
    id: '3',
    name: 'Debate Master',
    avatar: 1,
    title: 'Android vs iOS: Which is better?',
    description:
        'Let\'s settle this debate once and for all. Share your thoughts below!',
    postImageLink: 'https://picsum.photos/500/300?random=3',
    isDebate: true,
    upvotes: 200,
    downvotes: 29,
    isUpVote: false,
    isDownVote: false,
    comments: 87,
    clusters: clusters1,
    uploadTime: DateTime.now().subtract(Duration(hours: 8)),
  ),
  Post(
    id: '4',
    name: 'Food Blogger',
    avatar: 1,
    title: 'Easy 10-minute Pasta Recipe',
    description:
        'Perfect for when you\'re too tired to cook but want something delicious!',
    postVideoLink:
        'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4',
    isDebate: false,
    upvotes: 20,
    downvotes: 29,
    isUpVote: true,
    isDownVote: false,
    comments: 18,
    uploadTime: DateTime.now().subtract(Duration(hours: 12)),
  ),
  Post(
    id: '5',
    name: 'Fitness Coach',
    avatar: 1,
    title: 'Morning Workout Routine',
    description: 'Start your day right with these 5 simple exercises...',
    postImageLink: 'https://picsum.photos/500/300?random=4',
    isDebate: false,
    upvotes: 1000,
    downvotes: 200,
    isUpVote: false,
    isDownVote: true,
    comments: 42,
    uploadTime: DateTime.now().subtract(Duration(days: 1)),
  ),
];

List<Post> followingPosts = [
  Post(
    id: '101',
    name: 'Sarah Johnson',
    avatar: 1,
    title: 'My New Art Project',
    description:
        'After months of work, finally revealed my latest painting series!',
    postVideoLink:
        'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
    isDebate: false,
    upvotes: 109,
    downvotes: 0,
    isUpVote: true,
    isDownVote: false,
    comments: 15,
    uploadTime: DateTime.now().subtract(Duration(hours: 1)),
  ),
  Post(
    id: '102',
    name: 'Mike Chen',
    avatar: 1,
    title: 'Tech Startup Update',
    description:
        'We just secured our Series A funding! Big things coming soon.',
    isDebate: false,
    upvotes: 47,
    downvotes: 21,
    isUpVote: false,
    isDownVote: false,
    comments: 45,
    uploadTime: DateTime.now().subtract(Duration(hours: 3)),
  ),
  Post(
    id: '103',
    name: 'Alex Taylor',
    avatar: 1,
    title: 'Should remote work be the default?',
    description:
        'With offices reopening, let\'s discuss the future of work arrangements',
    isDebate: true,
    upvotes: 490,
    downvotes: 89,
    isUpVote: false,
    isDownVote: true,
    comments: 62,
    clusters: clusters2,
    uploadTime: DateTime.now().subtract(Duration(hours: 6)),
  ),
  Post(
    id: '104',
    name: 'David Kim',
    avatar: 1,
    title: 'Guitar Cover - Latest Pop Hit',
    description: 'Tried my hand at covering this week\'s #1 song',
    postVideoLink:
        'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    isDebate: false,
    upvotes: 430,
    downvotes: 90,
    isUpVote: true,
    isDownVote: false,
    comments: 12,
    uploadTime: DateTime.now().subtract(Duration(days: 1)),
  ),
  Post(
    id: '105',
    name: 'Emma Wilson',
    avatar: 1,
    title: 'Book Recommendation',
    description:
        'Just finished this amazing novel - highly recommend to all fiction lovers!',
    postImageLink: 'https://picsum.photos/500/300?random=105',
    isDebate: false,
    upvotes: 145,
    downvotes: 49,
    isUpVote: false,
    isDownVote: false,
    comments: 9,
    uploadTime: DateTime.now().subtract(Duration(days: 2)),
  ),
  Post(
    id: '106',
    name: 'James Rodriguez',
    avatar: 1,
    title: 'Photography Tips',
    description: '5 composition techniques that improved my photos instantly',
    postImageLink: 'https://picsum.photos/500/300?random=106',
    isDebate: true,
    clusters: clusters3,
    upvotes: 123,
    downvotes: 321,
    isUpVote: true,
    isDownVote: false,
    comments: 21,
    uploadTime: DateTime.now().subtract(Duration(days: 3)),
  ),
];
List<Post> trendingPosts = [
  Post(
    id: '207',
    name: 'AI Digest',
    avatar: 1,
    title: 'OpenAI GPT-5 Release Reactions',
    description:
        'The AI world is buzzing! What are your thoughts on GPT-5’s capabilities and risks?',
    isDebate: true,
    clusters: clusters1,
    upvotes: 850,
    downvotes: 125,
    isUpVote: false,
    isDownVote: true,
    comments: 78,
    uploadTime: DateTime.now().subtract(Duration(hours: 3)),
  ),
  Post(
    id: '208',
    name: 'Climate Now',
    avatar: 1,
    title: 'Youth Climate Protest in London',
    description:
        'Thousands of students marched today demanding action on climate change.',
    postImageLink: 'https://picsum.photos/500/300?random=7',
    isDebate: true,
    clusters: clusters2,
    upvotes: 710,
    downvotes: 60,
    isUpVote: true,
    isDownVote: false,
    comments: 66,
    uploadTime: DateTime.now().subtract(Duration(hours: 4)),
  ),
  Post(
    id: '209',
    name: 'MovieBuzz',
    avatar: 1,
    title: 'Met Gala 2025: Best Dressed?',
    description:
        'The most fashionable night of the year just ended. Who wore it best?',
    postImageLink: 'https://picsum.photos/500/300?random=8',
    isDebate: false,
    upvotes: 530,
    downvotes: 45,
    isUpVote: false,
    isDownVote: false,
    comments: 38,
    uploadTime: DateTime.now().subtract(Duration(hours: 10)),
  ),
  Post(
    id: '210',
    name: 'Crypto Insider',
    avatar: 1,
    title: 'Bitcoin Hits 90K: What’s Next?',
    description:
        'With Bitcoin reaching a new all-time high, is this just the beginning or the peak?',
    isDebate: true,
    clusters: clusters1,
    upvotes: 630,
    downvotes: 150,
    isUpVote: false,
    isDownVote: true,
    comments: 52,
    uploadTime: DateTime.now().subtract(Duration(hours: 5)),
  ),
  Post(
    id: '211',
    name: 'Health Beat',
    avatar: 1,
    title: 'Ozempic Craze – Good or Bad?',
    description:
        'Celebs and influencers are using Ozempic for weight loss. Is it safe or overhyped?',
    isDebate: true,
    clusters: clusters2,
    upvotes: 470,
    downvotes: 110,
    isUpVote: true,
    isDownVote: false,
    comments: 49,
    uploadTime: DateTime.now().subtract(Duration(hours: 9)),
  ),
];
