// ignore_for_file: file_names

import 'package:verbatica/model/Post.dart';

// List 1: 3 clusters
List<String> clusters1 = ['Technology', 'Science', 'Programming'];

// List 2: 4 clusters
List<String> clusters2 = ['Sports', 'Health', 'Fitness', 'Nutrition'];

// List 3: 2 clusters
List<String> clusters3 = ['Art', 'Music'];

List<Post> forYouPosts = [
  Post(
    id: '1',
    userId: 34,
    name: 'Tech News',
    avatar: 4,
    title: 'New Smartphone Released',
    description:
        'The latest flagship phone with revolutionary camera technology has been unveiled today.',
    postImageLink: 'https://picsum.photos/500/300?random=1',
    isDebate: false,
    upvotes: 245,
    downvotes: 22,
    isUpVote: true,
    isDownVote: false,
    comments: 32,
    uploadTime: DateTime.now().subtract(Duration(hours: 2)),
  ),
  Post(
    id: '2',
    userId: 35,
    name: 'Travel Enthusiast',
    avatar: 1,
    title: 'Hidden Beach in Thailand',
    description:
        'Found this amazing secluded beach that most tourists don\'t know about!',
    postImageLink: 'https://picsum.photos/500/300?random=2',
    isDebate: false,
    upvotes: 45,
    downvotes: 22,
    isUpVote: false,
    isDownVote: true,
    comments: 24,
    uploadTime: DateTime.now().subtract(Duration(hours: 5)),
  ),
  Post(
    id: '3',
    userId: 36,
    name: 'Debate Master',
    avatar: 2,
    title: 'Android vs iOS: Which is better?',
    description:
        'Let\'s settle this debate once and for all. Share your thoughts below!',
    postImageLink: 'https://picsum.photos/500/300?random=3',
    isDebate: true,
    upvotes: 200,
    downvotes: 29,
    isUpVote: false,
    isDownVote: false,
    comments: 87,
    clusters: clusters1,
    uploadTime: DateTime.now().subtract(Duration(hours: 8)),
  ),
  Post(
    id: '4',
    userId: 37,
    name: 'Food Blogger',
    avatar: 1,
    title: 'Easy 10-minute Pasta Recipe',
    description:
        'Perfect for when you\'re too tired to cook but want something delicious!',
    postVideoLink:
        'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4',
    isDebate: false,
    upvotes: 20,
    downvotes: 29,
    isUpVote: true,
    isDownVote: false,
    comments: 18,
    uploadTime: DateTime.now().subtract(Duration(hours: 12)),
  ),
  Post(
    id: '5',
    userId: 38,
    name: 'Fitness Coach',
    avatar: 7,
    title: 'Morning Workout Routine',
    description: 'Start your day right with these 5 simple exercises...',
    postImageLink: 'https://picsum.photos/500/300?random=4',
    isDebate: false,
    upvotes: 1000,
    downvotes: 200,
    isUpVote: false,
    isDownVote: true,
    comments: 42,
    uploadTime: DateTime.now().subtract(Duration(days: 1)),
  ),
];

List<Post> followingPosts = [
  Post(
    id: '101',
    userId: 39,
    name: 'Sarah Johnson',
    avatar: 6,
    title: 'My New Art Project',
    description:
        'After months of work, finally revealed my latest painting series!',
    postVideoLink:
        'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
    isDebate: false,
    upvotes: 109,
    downvotes: 0,
    isUpVote: true,
    isDownVote: false,
    comments: 15,
    uploadTime: DateTime.now().subtract(Duration(hours: 1)),
  ),
  Post(
    id: '102',
    userId: 40,
    name: 'Mike Chen',
    avatar: 5,
    title: 'Tech Startup Update',
    description:
        'We just secured our Series A funding! Big things coming soon.',
    isDebate: false,
    upvotes: 47,
    downvotes: 21,
    isUpVote: false,
    isDownVote: false,
    comments: 45,
    uploadTime: DateTime.now().subtract(Duration(hours: 3)),
  ),
  Post(
    id: '103',
    userId: 41,
    name: 'Alex Taylor',
    avatar: 4,
    title: 'Should remote work be the default?',
    description:
        'With offices reopening, let\'s discuss the future of work arrangements',
    isDebate: true,
    upvotes: 490,
    downvotes: 89,
    isUpVote: false,
    isDownVote: true,
    comments: 62,
    clusters: clusters2,
    uploadTime: DateTime.now().subtract(Duration(hours: 6)),
  ),
  Post(
    id: '104',
    userId: 42,
    name: 'David Kim',
    avatar: 3,
    title: 'Guitar Cover - Latest Pop Hit',
    description: 'Tried my hand at covering this week\'s #1 song',
    postVideoLink:
        'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    isDebate: false,
    upvotes: 430,
    downvotes: 90,
    isUpVote: true,
    isDownVote: false,
    comments: 12,
    uploadTime: DateTime.now().subtract(Duration(days: 1)),
  ),
  Post(
    id: '105',
    userId: 43,
    name: 'Emma Wilson',
    avatar: 1,
    title: 'Book Recommendation',
    description:
        'Just finished this amazing novel - highly recommend to all fiction lovers!',
    postImageLink: 'https://picsum.photos/500/300?random=105',
    isDebate: false,
    upvotes: 145,
    downvotes: 49,
    isUpVote: false,
    isDownVote: false,
    comments: 9,
    uploadTime: DateTime.now().subtract(Duration(days: 2)),
  ),
  Post(
    id: '106',
    userId: 44,
    name: 'James Rodriguez',
    avatar: 2,
    title: 'Photography Tips',
    description: '5 composition techniques that improved my photos instantly',
    postImageLink: 'https://picsum.photos/500/300?random=106',
    isDebate: true,
    clusters: clusters3,
    upvotes: 123,
    downvotes: 321,
    isUpVote: true,
    isDownVote: false,
    comments: 21,
    uploadTime: DateTime.now().subtract(Duration(days: 3)),
  ),
];
