import 'package:verbatica/model/user.dart';

final List<User> dummySearchedUsers = [
  User(
    userId: 'u1',
    username: 'goofyPanda',
    karma: 1200,
    followers: 300,
    following: 150,
    joinedDate: DateTime(2022, 5, 12),
    country: 'USA',
    about: 'Lover of discussions and debates.',
    avatarId: 1,
  ),
  User(
    userId: 'u2',
    username: 'lazyTiger',
    karma: 980,
    followers: 200,
    following: 180,
    joinedDate: DateTime(2021, 3, 8),
    country: 'Canada',
    about: 'Just here to learn new things.',
    avatarId: 2,
  ),
  User(
    userId: 'u3',
    username: 'quietOtter',
    karma: 1500,
    followers: 450,
    following: 210,
    joinedDate: DateTime(2020, 7, 20),
    country: 'UK',
    about: 'Political enthusiast.',
    avatarId: 3,
  ),
  User(
    userId: 'u4',
    username: 'sneakyKoala',
    karma: 760,
    followers: 100,
    following: 90,
    joinedDate: DateTime(2023, 1, 1),
    country: 'Germany',
    about: 'Into tech and gadgets.',
    avatarId: 4,
  ),
  User(
    userId: 'u5',
    username: 'happyFalcon',
    karma: 1100,
    followers: 330,
    following: 300,
    joinedDate: DateTime(2022, 11, 18),
    country: 'Australia',
    about: 'Exploring diverse opinions.',
    avatarId: 5,
  ),
  User(
    userId: 'u6',
    username: 'grumpyLlama',
    karma: 890,
    followers: 220,
    following: 140,
    joinedDate: DateTime(2021, 6, 10),
    country: 'Spain',
    about: 'Always curious.',
    avatarId: 6,
  ),
  User(
    userId: 'u7',
    username: 'wittyPenguin',
    karma: 1320,
    followers: 400,
    following: 250,
    joinedDate: DateTime(2023, 2, 14),
    country: 'South Korea',
    about: 'Passionate about culture and philosophy.',
    avatarId: 1,
  ),
  User(
    userId: 'u8',
    username: 'sleepyCroc',
    karma: 670,
    followers: 90,
    following: 60,
    joinedDate: DateTime(2022, 9, 30),
    country: 'Mexico',
    about: 'Here for good conversations.',
    avatarId: 2,
  ),
  User(
    userId: 'u9',
    username: 'curiousYak',
    karma: 1570,
    followers: 500,
    following: 280,
    joinedDate: DateTime(2020, 12, 25),
    country: 'Brazil',
    about: 'Moderator and community helper.',
    avatarId: 3,
  ),
  User(
    userId: 'u10',
    username: 'braveTurtle',
    karma: 720,
    followers: 180,
    following: 190,
    joinedDate: DateTime(2021, 8, 5),
    country: 'India',
    about: 'Enjoys healthy debates.',
    avatarId: 4,
  ),
];
